  // Cache DOM elements and expose globally
  window.dom = {
    btnReceipts: document.getElementById('btn-receipts'),
    btnReports: document.getElementById('btn-reports'),
    btnIngredients: document.getElementById('btn-ingredients'),
	btnRecipes: document.getElementById('btn-recipes'),
    modal: document.getElementById('modal'),
    cancelBtn: document.getElementById('cancel-btn'),
    submitBtn: document.getElementById('submit-btn'),
    vendor: document.getElementById('vendor'),
    amount: document.getElementById('amount'),
    method: document.getElementById('method'),
    date: document.getElementById('date'),
    invoice: document.getElementById('invoice'),
    items: document.getElementById('items'),
    receiptImage: document.getElementById('receipt-image'),
    imagePreview: document.getElementById('image-preview'),
    downloadImageBtn: document.getElementById('download-image'),
    mainContent: document.getElementById('main-content'),
	recipeName: document.getElementById('recipe-name'),
	recipeDescription: document.getElementById('recipe-description'),
	recipeModal: document.getElementById('recipe-modal'),
	recipeSubmitBtn: document.getElementById('recipe-submit-btn'),
	recipeCancelBtn: document.getElementById('recipe-cancel-btn'),
	recipeForm: document.getElementById('recipe-form'),
	materialCost: document.getElementById('material-cost'),
  };